version: '3.8'
services:
  postgres_db:
    container_name: postgres_db_app
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_app:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring

  mail_dev:
    container_name: mail_dev
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  volume_postgres_db_app:
    external: false
networks:
  spring:
    driver: bridge