services:
  postgres_db:
    container_name: postgres_db_app
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres_db_app:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres | grep 'accepting connections' || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - spring
  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev","--import-realm" ]
    volumes:
      - keycloak_reamls_data:/opt/keycloak/data/
    networks:
      - spring
volumes:
  volume_postgres_db_app:
    external: false
  keycloak_reamls_data:
    external: false
networks:
  spring:
    driver: bridge