spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/
  port: 8088

application:
  security:
    jwt:
      expiration: 63000000
      secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account